// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE3oeyaay4degaApyMZWomOIxT3xPEzIw',
    appId: '1:209325871242:web:dd001de1aa76779bb6dd73',
    messagingSenderId: '209325871242',
    projectId: 'techniche-269b1',
    authDomain: 'techniche-269b1.firebaseapp.com',
    storageBucket: 'techniche-269b1.firebasestorage.app',
    measurementId: 'G-2KK2STP7QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvkXzgZMaj0p9FKebFJubg0CSYxYG5uig',
    appId: '1:209325871242:android:9765effeb0961737b6dd73',
    messagingSenderId: '209325871242',
    projectId: 'techniche-269b1',
    storageBucket: 'techniche-269b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLI_U0Bzd3-6-TEfbFN539EHk2Pa84bww',
    appId: '1:209325871242:ios:c3915e302e702535b6dd73',
    messagingSenderId: '209325871242',
    projectId: 'techniche-269b1',
    storageBucket: 'techniche-269b1.firebasestorage.app',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLI_U0Bzd3-6-TEfbFN539EHk2Pa84bww',
    appId: '1:209325871242:ios:c3915e302e702535b6dd73',
    messagingSenderId: '209325871242',
    projectId: 'techniche-269b1',
    storageBucket: 'techniche-269b1.firebasestorage.app',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE3oeyaay4degaApyMZWomOIxT3xPEzIw',
    appId: '1:209325871242:web:e4933285fb03c532b6dd73',
    messagingSenderId: '209325871242',
    projectId: 'techniche-269b1',
    authDomain: 'techniche-269b1.firebaseapp.com',
    storageBucket: 'techniche-269b1.firebasestorage.app',
    measurementId: 'G-8GC3WD55YQ',
  );
}
